-- Script PostgreSQL para executar no Editor SQL do Supabase

CREATE TABLE public."Usuarios" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "NomeCompleto" text NOT NULL,
    "Email" text NOT NULL UNIQUE,
    "SenhaHash" text NOT NULL,
    "DataCriacao" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    "Ativo" boolean DEFAULT true NOT NULL
);

-- Habilitando RLS (Row Level Security) se precisar (recomendado)
-- ALTER TABLE public."Usuarios" ENABLE ROW LEVEL SECURITY;

-- Política simples para permitir leitura/inserção anônima para testes
-- (Cuidado em produção: você pode querer proteger essas rotas)
CREATE POLICY "Permitir leitura/escrita anonima" 
ON public."Usuarios" 
FOR ALL 
USING (true)
WITH CHECK (true);
