-- ==========================================
-- SCRIPT DE CRIAÇÃO (APENAS NOVAS TABELAS)
-- ==========================================

-- Tabela de Receitas (Vistorias e Entradas)
CREATE TABLE IF NOT EXISTS public."Receitas" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "category" text NOT NULL,          
    "placa" text NOT NULL,             
    "cliente" text,                    
    "nf" text,                         
    "pagamento" text,                  
    "amountBruto" numeric(10,2) NOT NULL, 
    "amountLiquido" numeric(10,2) NOT NULL,
    "amount" numeric(10,2) NOT NULL,   -- Mantido aqui para compatibilidade com o codigo
    "date" text NOT NULL,              -- Mantido como texto (YYYY-MM-DD) para casar direto com javascript
    "observacao" text,
    "user_id" bigint REFERENCES public."Usuarios"("Id")
);

-- Tabela de Despesas (Contas a Pagar e Custos Operacionais)
CREATE TABLE IF NOT EXISTS public."Despesas" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "category" text NOT NULL,          
    "description" text NOT NULL,       
    "amount" numeric(10,2) NOT NULL,   
    "vencimento" text NOT NULL,        
    "status" text NOT NULL,            
    "date" text NOT NULL,              
    "observacao" text,
    "user_id" bigint REFERENCES public."Usuarios"("Id")
);

-- Desabilitando RLS para facilitar os testes agora no começo
ALTER TABLE public."Receitas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Despesas" ENABLE ROW LEVEL SECURITY;

-- Políticas Provisórias para Leitura e Escrita Direta do Javascript (Testes Locais)
DROP POLICY IF EXISTS "Permitir leitura/escrita anonima receitas" ON public."Receitas";
CREATE POLICY "Permitir leitura/escrita anonima receitas" ON public."Receitas" FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Permitir leitura/escrita anonima despesas" ON public."Despesas";
CREATE POLICY "Permitir leitura/escrita anonima despesas" ON public."Despesas" FOR ALL USING (true) WITH CHECK (true);
