-- ==========================================
-- SCRIPT DE CRIAÇÃO (SISTEMA DE LOGS / AUDITORIA)
-- ==========================================

-- Tabela de Logs de Auditoria
CREATE TABLE IF NOT EXISTS public."LogsAuditoria" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" bigint REFERENCES public."Usuarios"("Id"),
    "acao" text NOT NULL,             -- Ex: 'CRIAR_RECEITA', 'DELETAR_DESPESA'
    "mensagem" text NOT NULL,         -- Texto descritivo para humanos
    "data_hora" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Desabilitar restrições RLS de inicio para simplificar requisição Javascript Client
ALTER TABLE public."LogsAuditoria" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir leitura/escrita anonima logs" ON public."LogsAuditoria";
CREATE POLICY "Permitir leitura/escrita anonima logs" 
ON public."LogsAuditoria" 
FOR ALL 
USING (true) 
WITH CHECK (true);
